// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6cqgnWb1MQiGDNO43MatnhAYuPEcieO4',
    appId: '1:886868459654:web:93051dcc63e25865551107',
    messagingSenderId: '886868459654',
    projectId: 'todo-app-fad87',
    authDomain: 'todo-app-fad87.firebaseapp.com',
    storageBucket: 'todo-app-fad87.firebasestorage.app',
    measurementId: 'G-PMFLZEVPPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUlTLAuzJDhygFQIScsHVa6aqQh2VOdds',
    appId: '1:886868459654:android:5c6ebaa320a1520b551107',
    messagingSenderId: '886868459654',
    projectId: 'todo-app-fad87',
    storageBucket: 'todo-app-fad87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Fv4F_P8zRAe4vGjBqooUOK2L6U8G6M8',
    appId: '1:886868459654:ios:4d66fbf906d1a858551107',
    messagingSenderId: '886868459654',
    projectId: 'todo-app-fad87',
    storageBucket: 'todo-app-fad87.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
